name: Deploy Files

on:
  push:
    branches:
      - main
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "full"

jobs:

  build-deploy-main:
    name: "Build then deploy main branch"
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Node and build site"
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"
      - run: npm install
      - run: npm run build-storybook
      - run: npm run build-css
      - run: npx @11ty/eleventy

      - name: "Deploy main branch"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-port: 22
          remote-host: ${{ secrets.IONOS_SFTP_HOST }}
          remote-user: ${{ secrets.IONOS_SFTP_USER }}
          ssh-private-key: ${{ secrets.IONOS_SFTP_KEY }}
          local-path: "./_site/"
          remote-path: "/"
